make distclean
perl Makefile.PL
$(make)
cd Tests
clang -c  -F/opt/CB  -v -arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE  -Wall -O3   -Wall -O3   -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\"  "-I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE" CBThreadTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE  -Wall -O3   -Wall -O3   -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" "-I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE" CBSuper.m
clang -c  -F/opt/CB  -v -arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE  -Wall -O3   -Wall -O3   -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\"  "-I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE" CBExceptionTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE  -Wall -O3   -Wall -O3   -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\"  "-I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE" CBStructureTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE  -Wall -O3   -Wall -O3   -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\"  "-I/opt/local/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE" CBPropertyTests.m
cd ..
make
make test

