make distclean
perl Makefile.PL
cd Tests
clang -c  -F/opt/CB  -v -arch armv7 -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" CBThreadTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" CBPropertyTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" CBSuper.m
clang -c  -F/opt/CB  -v -arch armv7 -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" CBExceptionTests.m
clang -c  -F/opt/CB  -v -arch armv7 -arch arm64 -miphoneos-version-min=8.0 -isysroot/opt/sdks/Latest.sdk -fno-common -Wall -O3 -pipe -Os -fno-strict-aliasing -fstack-protector-strong -I/opt/sdks/Latest.sdk/usr/include  -I/opt/local/include -I/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -isysroot/opt/sdks/Latest.sdk -L/opt/sdks/Latest.sdk/usr/lib -L/opt/sdks/Latest.sdk/usr/lib/system -L/opt/local/lib  -Wl,-headerpad_max_install_names -fstack-protector-strong -ObjC -lobjc -L/opt/local/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -DVERSION=\"1.2.0\" -DXS_VERSION=\"1.2.0\" CBStructureTests.m
cd ..
make
make test
make install
